FROM node:20 AS build 
WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . . 
ENV NODE_OPTIONS=--openssl-legacy-provider
RUN npm run build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build /app/build .

EXPOSE 80 